development:
  adapter: postgresql
  database: isbn_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: isbn_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: isbn_production
  pool: 5
  timeout: 5000
