# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6114bebded85ed06cd8d604bdcd23a730ffee789a993c4ccf1b63127e44be68e9a57320c7044d18a3e6ac0fe232639c0917a46ac38a8dc0aef480b602cee7781

test:
  secret_key_base: 121d98f75ae20e62ca17996182858aeb0fc0899f66a96a2c00e2c969bb2d48bc5885b013db6f3bfb4276788a090fb110fa3b4b21fe40f35e68e38228683ace59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
